service: dmbp-editor 

image: editor

servers:
  web:
    hosts:
      - 0.0.0.0
    labels:
      traefik.http.routers.dmbp-editor.entrypoints: websecure
      traefik.http.routers.dmbp-editor.rule: Host(`editor.example.com`)
      traefik.http.routers.dmbp-editor.tls.certresolver: letsencrypt

registry:
  server: dmbpcr.azurecr.io
  username: kamal
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: azureuser

builder:
  dockerfile: "../Dockerfile"
  context: ".."

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entryPoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "email@example.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

healthcheck:
  path: /ok
  port: 80
